# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159JP6mp2t3jPlO0Kyfra_WIv0g8FYCxm
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Configuração da Página
st.set_page_config(page_title="Calculadora Prognóstica TMO Pediátrico", page_icon="🏥")

# Título e Cabeçalho
st.title("🏥 Escore Prognóstico Pediátrico Simplificado (EPPS)")
st.markdown("""
Esta ferramenta estima a estratificação de risco para pacientes pediátricos submetidos a
Transplante de Medula Óssea Alogênico, baseada em coorte retrospectiva (N=187).
**Uso exclusivo para pesquisa e suporte à decisão clínica.**
""")

st.divider()

# --- BARRA LATERAL (ENTRADA DE DADOS) ---
st.sidebar.header("Dados do Paciente")

idade = st.sidebar.number_input("Idade do Receptor (anos)", min_value=0.0, max_value=25.0, value=9.0, step=0.1)
dose = st.sidebar.number_input("Dose de Células CD34+ (×10⁶/kg)", min_value=0.0, max_value=50.0, value=12.0, step=0.1)
risco_doenca = st.sidebar.selectbox("Classificação de Risco da Doença", ["Risco Padrão", "Alto Risco"])

# Definição do Cutoff da Dose (Baseado na Mediana do Estudo)
MEDIANA_DOSE_ESTUDO = 11.9

# --- CÁLCULO DO SCORE (BACKEND) ---
pontos = 0
detalhes = []

# 1. Fator Idade (> 10 anos)
if idade > 10:
    pontos += 1
    detalhes.append("❌ Idade > 10 anos (+1 ponto)")
else:
    detalhes.append("✅ Idade ≤ 10 anos (0 pontos)")

# 2. Fator Dose (< Mediana)
if dose < MEDIANA_DOSE_ESTUDO:
    pontos += 1
    detalhes.append(f"❌ Dose CD34 < {MEDIANA_DOSE_ESTUDO} (+1 ponto)")
else:
    detalhes.append("✅ Dose CD34 Alta (0 pontos)")

# 3. Fator Risco da Doença
if risco_doenca == "Alto Risco":
    pontos += 1
    detalhes.append("❌ Doença de Alto Risco (+1 ponto)")
else:
    detalhes.append("✅ Doença de Risco Padrão (0 pontos)")

# --- EXIBIÇÃO DOS RESULTADOS ---

col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("Resultado")
    st.metric(label="Pontuação Total", value=f"{pontos}/3")

    if pontos == 0:
        st.success("BAIXO RISCO")
        prob_sobrevida = "High (> 65%)"
        cor_grafico = "green"
    elif pontos <= 2:
        st.warning("RISCO INTERMEDIÁRIO")
        prob_sobrevida = "Medium (50-60%)"
        cor_grafico = "orange"
    else:
        st.error("ALTO RISCO")
        prob_sobrevida = "Low (< 45%)"
        cor_grafico = "red"

    st.markdown("### Detalhamento:")
    for item in detalhes:
        st.write(item)

with col2:
    st.subheader("Curva de Sobrevida Estimada")
    # Simulação Visual das Curvas do Estudo (Para ilustração)
    t = np.linspace(0, 5, 100) # 5 Anos

    # Curvas matemáticas aproximadas baseadas nos seus dados reais
    if pontos == 0:
        s = np.exp(-0.08 * t) # Decaimento lento (Verde)
        label_curve = "Perfil Baixo Risco"
    elif pontos <= 2:
        s = np.exp(-0.15 * t) # Decaimento médio (Laranja)
        label_curve = "Perfil Intermediário"
    else:
        s = np.exp(-0.35 * t) # Decaimento rápido (Vermelho)
        label_curve = "Perfil Alto Risco"

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(t, s, color=cor_grafico, linewidth=3, label=label_curve)
    ax.set_ylim(0, 1.05)
    ax.set_xlabel("Anos Pós-Transplante")
    ax.set_ylabel("Probabilidade de Sobrevida")
    ax.grid(True, alpha=0.3)
    ax.legend()
    ax.fill_between(t, s, color=cor_grafico, alpha=0.1)

    st.pyplot(fig)

st.info(f"**Interpretação:** Pacientes com escore {pontos} apresentaram historicamente perfil de sobrevida correspondente à curva acima.")